# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b79accad2adcc2874d34057ca9a1239130164aa4d086a1186b9ba678eded5dc6853ab0f75be69540c808c901d5348205a02113b193904f2baf12f13806aff60

test:
  secret_key_base: 2ee726c82d463df7e4471aee8063b9db756a1d2ef449a27c66ddaef702ea3a1926f4e5bd2d0d7731d573dbc8f5cabe774a4b356e2468baac4d11797223ec02a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
